Fork from upstream and move customization
teamdigitale/cla-assistant pull request #1
Opened 2020-10-22 08:45 UTC by sebbalex

As discussed we need to be connected with upstream repository, this PR aims to import the customization applied for our needs.
Old repo is still available for a while: https://github.com/teamdigitale/cla-assistant-old

* http-s proxy support
* example env for docker-compose
* styling
* refactor: internalized assets, dedicated grunt task to copy them
* set up CI with Azure Pipelines

2020-10-22 16:12 UTC, bfabio requested changes
Can we group all the commits that need to be squashed? Something along the lines of:

# chore: use Azure Pipelines CI
`fix: removing old CI integration`
`fix: removing old CI pipeline`
`Set up CI with Azure Pipelines `
`Update azure-pipelines.yml for Azure Pipelines`

# chore: add docker-compose support
`Update docker-compose`
`Update port docker-compose.yml`
`adding example env for docker-compose`
`feat: docker-compose`

# feat: custom style
`refactor: login page debrand`
`refactor: login page`
`fix: some styling`

# refactor: local resources
`refactor: internalized some other assets, cleaning`
`fix: removing fontawesome.css`
`refactor: adding fontawesome using npm`
`refactor: adding grunt task to copy static asset libs`
`refactor: ignoring packet manager assets generated`
`refactor: static octicons`
`refactor: static angular lib map`

# style: unused code cleanup
`fix: removing unused parapraph`
`fix: removing commented code`

# chore: custom GitHub files
`refactor: removing github related old files`
`fix: typo`

We should drop `trigger CD`.

2020-10-23 11:10 UTC, bfabio requested changes
Aren't the files in `client/assets/` generated at build? We should keep them out of the repo, if possible.

2020-10-23 11:10 UTC, bfabio commented on .env.docker
> +HTTPS_PROXY=http://localhost:3128
Shouldn't we use only `HTTP_PROXY`? I'm assuming we should in the next comments. If not, ignore those.

2020-10-23 11:10 UTC, bfabio commented on .env.example
> +export HTTPS_PROXY=http://localhost:3128
```suggestion
```

2020-10-23 11:10 UTC, bfabio commented on README.md
> +
```suggestion
```

2020-10-23 11:10 UTC, bfabio commented on src/client/assets/styles/_landing-page.scss
> +  // background-image: url('/assets/images/background.jpg');
```suggestion
```

2020-10-23 11:10 UTC, bfabio commented on src/client/assets/styles/_landing-page.scss
> +  // height: 100vH;
```suggestion
```

2020-10-23 11:10 UTC, bfabio commented on src/client/assets/styles/_landing-page.scss
> +  // color: $text-invert;
```suggestion
```

2020-10-23 13:03 UTC, sebbalex commented on src/server/middleware/setupProxy.js
> +console.log("setup proxy to: ", env["http_proxy"], env["HTTP_PROXY"]);
we don't need to supports both cases, removed lowercase.

2020-10-23 13:32 UTC, sebbalex commented
> Aren't the files in `client/assets/` generated at build? We should keep them out of the repo, if possible.

Just few of them are generated and they are already out of it.

2020-10-23 15:12 UTC, bfabio approved these changes
lgtm :rocket:

2020-10-23 15:27 UTC, merged